name: "Publish GitHub Action"
on: 
  workflow_run:
    workflows: [Publish GitHub Action]
    types: 
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: tgymnich/publish-github-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}